config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  devise_for :users
  root to: 'rvs#index'

  resources :rvs, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create, :edit, :update]
  end
  resources :bookings, only: [:index]
  get "myrvs", to: 'rvs#my_rvs'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :rv
  belongs_to :user
  validates :price, presence: true
  validates :check_in_on, presence: true
  validates :check_out_on, presence: true
  validates :status, presence: true, inclusion: { in: ["Pending", "Accepted", "Cancelled"] }
  validates :rating, inclusion: { in: [ 1, 2, 3, 4, 5], allow_nil: true }
  # commented below in order to seed past bookings
  # validate :date_validation
  # validate :date_is_past


  def date_validation
    if check_out_on.present? &&  check_in_on.present? && check_out_on < check_in_on
      errors.add(:check_out_on, "can't be before check-in")
    end
  end

  def date_is_past
    if check_in_on.present? && check_in_on < Date.today
      errors.add(:check_in_on, "can't be in the past")
    end
  end
end

app/models/rv.rb
class Rv < ApplicationRecord
  $RV_KIND = ["Standard", "Large", "Compact", "Truck camper"]
  $MAX_GUESTS = 8
  has_many :bookings
  has_attachment :photo
  belongs_to :user
  validates :name, presence: true, uniqueness: true
  validates :localisation, presence: true
  validates :kind, presence: true, inclusion: { in: $RV_KIND }
  validates :number_of_beds, presence: true, numericality: { only_integer: true, less_than_or_equal_to: $MAX_GUESTS }
  validates :number_of_guests, presence: true, numericality: { only_integer: true }
  validates :price_per_night, presence: true
  validates :min_stay, presence: true, numericality: { only_integer: true, greater_than: 1 }
  validate :guests_inf_to_beds
  geocoded_by :localisation
  after_validation :geocode

  def guests_inf_to_beds
    if number_of_beds.present? && number_of_guests.present? && number_of_guests > number_of_beds
      errors.add(:number_of_guests, "can't be more than number of beds")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rvs, dependent: :destroy
  has_many :bookings
  has_attachment :photo
  validates :first_name, presence: true, length: { minimum: 1 }
  validates :last_name, presence: true, length: { minimum: 1 }
  validates :email, presence: true, uniqueness: true
  validates_format_of :phone_number, :with => /\A\+?[\d\s{1}\/\(\)\-]{8,}\Z/, :on => :create, :message=>  "must be more than 7 digits"
  validates :date_of_birth, presence: true
  validate :validate_age

  private

  def validate_age
    if date_of_birth.present? && date_of_birth > 18.years.ago.to_date
      errors.add(:date_of_birth, 'You should be over 18 years old.')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :date_of_birth, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name,:last_name, :date_of_birth, :phone_number])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @rv = Rv.find(params[:rv_id])
    @booking = Booking.new
  end

  def create
    @rv = Rv.find(params[:rv_id])
    @days = (params[:booking][:check_out_on].to_date - params[:booking][:check_in_on].to_date).to_i
    @booking = Booking.new
    if @days >= @rv.min_stay
      @price = @days * @rv.price_per_night
      @booking = Booking.new(booking_params)
      @booking.price = @price
      @booking.rv = @rv
      @booking.user = current_user
      if @booking.save
        redirect_to bookings_path
      else
        flash.now[:alert] = @booking.errors.full_messages[0]
        render :new
      end
    else
      flash.now[:alert] = "Stay can't be shorter than #{@rv.min_stay} days"
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.review = params[:booking][:review]
    @booking.rating = params[:booking][:rating]
    @booking.status = params[:booking][:status]
    if @booking.save
      redirect_to myrvs_path
    else
       render :show
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:check_in_on, :check_out_on, :rating, :review, :status)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
end

app/controllers/rvs_controller.rb
class RvsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @rvs = Rv.all
    @rvs = Rv.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@rvs) do |rv, marker|
      marker.lat rv.latitude
      marker.lng rv.longitude
      # marker.infowindow render_to_string(partial: "/rvs/map_box", locals: { rv: rv })
    end
  end

  def show
    @rv = Rv.find(params[:id])
    @booking = Booking.new
    @hash = Gmaps4rails.build_markers(@rv) do |rv, marker|
      marker.lat rv.latitude
      marker.lng rv.longitude
      # marker.infowindow render_to_string(partial: "/rvs/map_box", locals: { rv: rv })
    end
  end

  def new
    @rv = Rv.new
  end

  def create
    @rv = Rv.new(rv_params)
    @rv.user = current_user
    if @rv.save
      redirect_to rv_path(@rv)
    else
      render :new
    end
  end

  def edit
    @rv = Rv.find(params[:id])
  end

  def update
    @rv = Rv.find(params[:id])
    @rv.name = params[:rv][:name]
    @rv.localisation = params[:rv][:localisation]
    @rv.kind = params[:rv][:kind]
    @rv.number_of_beds = params[:rv][:number_of_beds]
    @rv.number_of_guests = params[:rv][:number_of_guests]
    @rv.price_per_night = params[:rv][:price_per_night]
    @rv.min_stay = params[:rv][:min_stay]
    @rv.photo = params[:rv][:photo]
    @rv.user = current_user
    if @rv.save
      redirect_to rv_path(@rv)
    else
      render :edit
    end
  end

  def my_rvs
    @my_rvs = current_user.rvs
  end
  def destroy
    @rv = Rv.find(params[:id])
    @rv.destroy
    redirect_to myrvs_path
  end

  private

  def rv_params
    params.require(:rv).permit(:name, :localisation, :kind, :number_of_beds, :number_of_guests, :price_per_night, :min_stay, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_edit.html.erb
<%= simple_form_for @booking do |f|%>
  <%= f.input :review %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

app/views/bookings/_new.html.erb
<%= simple_form_for @booking, url: rv_bookings_path(@rv), method: :post do |f| %>
  <p>From</p>
  <p><%= f.text_field :check_in_on, "data-provide" => "datepicker",  "data-date-format" => "dd/mm/yyyy" %></p>
  <p>To</p>
  <p><%= f.text_field :check_out_on, "data-provide" => "datepicker", "data-date-format" => "dd/mm/yyyy"  %></p>
  <%= f.submit %>
<% end %>

app/views/bookings/index.html.erb
<div class="wrapper", style="background-image: linear-gradient(-225deg, rgba(0,101,168,0) 0, rgba(70,70,70,0.3) 50%), url('https://source.unsplash.com/llNrizoUL84');background-size:cover;height:100vh;color:white;">

<div class="container">
  <div class="header" style="margin-bottom: 48px;">
    <h1 class="text-center">My bookings</h1>
  </div>


  <% @bookings.each do |booking| %>
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <div class="booking">
            <p><strong><%= link_to booking.rv.name, rv_path(booking.rv)%></strong></p>
            <p>From <%= booking.check_in_on %></p>
            <p>To <%= booking.check_out_on %></p>
            <p>Price <%= booking.price %>$</p>
            <p>Status: <%= booking.status %></p>
        </div>
      </div>
    </div>
  <% end %>


</div>
</div>

app/views/bookings/show.html.erb
<h1><%= @booking.price %></h1>

<% if @booking.check_out_on < Date.today + 10 %>
  <% if  @booking.rating.nil? %>
    <%= render "bookings/edit" %>
  <% else %>
    <p><%= @booking.review %></p>
    <p><%= "*" * @booking.rating %></p>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MC RVs</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,900" rel="stylesheet">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <% if current_page?(root_path) %>
      <%= render 'shared/banner' %>
    <% end %>

    <%= yield %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %> <!-- Append this after the main `javascript_include_tag`. -->
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render '/rvs/index.html.erb' %>

app/views/rvs/_form.html.erb
<div class="container text-center" style="margin-top: 20px;">
  <h1> Create a new RV</h1>
  <div class="row text-left">
    <div class = "col-xs-12 col-sm-6 col-sm-offset-3">
      <div style="background-color: rgb(230, 230, 230); border-raius: 3px; box-shadow: 1px 1px 12px #AAAAAA; padding: 15px;">
        <%= simple_form_for @rv do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :attachinary %>
        <%= f.input :kind %>
        <%= f.input :localisation %>
        <%= f.input :number_of_beds %>
        <%= f.input :number_of_guests %>
        <%= f.input :price_per_night %>
        <%= f.input :min_stay %>
        <%= f.submit %>
      <% end %>

      </div>
    </div>
  </div>
</div>

app/views/rvs/_index.html.erb
<div class="header-main text-center">
    <h1>All RVs available for bookings</h1>
</div>
<div class="container">
  <div class="row">
    <% if @rvs.length == 0 %>
      <div class="col-xs-12">
        <p>Sorry, no RVs available<p>
      </div>
    <% else %>
      <% @rvs.each do |rv| %>
        <div class="col-xs-12 col-sm-6 col-md-4 text-center" >
          <% if rv.photo? %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url('<%= cl_image_path rv.photo.path, height: 300, width: 500, crop: :fill %>')">
          <% else %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://source.unsplash.com/FjtE9VKlKg4/500x300');">
          <% end %>
          <div class="card-category"><%= rv.kind %></div>
          <div class="card-description">
            <h2><%= rv.name %></h2>
          </div>
          <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
          <%= link_to "", rv_path(rv), class: "card-link" %>
        </div>

        </div>
      <% end %>
    <% end %>
  </div>
  <br>
  <%= link_to "Put a RV up for rental", new_rv_path, :class => "btn btn-primary" %>
</div>

app/views/rvs/edit.html.erb
<%= render 'form' %>

app/views/rvs/index.html.erb
<div class="container">
  <div id="map" style="width: 100%; height: 400px;" ></div>
  <% content_for(:after_js) do %>
    <script>
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
      var input = document.getElementById('pac-input');
        var searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

    </script>
  <% end %>
  <div class="row">
    <% if @rvs.length == 0 %>
      <div class="col-xs-12">
        <p>Sorry, no RVs available<p>
      </div>
    <% else %>
      <% @rvs.each do |rv| %>
        <div class="col-xs-12 col-sm-6 col-md-4 text-center" >
          <% if rv.photo? %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url('<%= cl_image_path rv.photo.path, height: 300, width: 500, crop: :fill %>')">
          <% else %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://source.unsplash.com/FjtE9VKlKg4/500x300');">
          <% end %>
          <div class="card-category"><%= rv.kind %></div>
          <div class="card-description">
            <h2><%= rv.name %></h2>
            <p><%= rv.localisation %></p>
          </div>
          <div class="card-price">
            <p><%= rv.price_per_night %> € </p>
          </div>
          <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
          <%= link_to "", rv_path(rv), class: "card-link" %>
        </div>

        </div>
      <% end %>
    <% end %>
  </div>
  </div>
</div>

app/views/rvs/my_rvs.html.erb
<div class="container">
  <h1>My RVs</h1>

    <% @my_rvs.each do |rv| %>
    <div class= "rv">

      <div class="inline" >

          <h3><%= link_to rv.name, rv_path(rv) %></h3>

          <div class="placeholder"></div>


          <h3><%= link_to "Edit", edit_rv_path(rv)%></h3>

          <div class="placeholder"></div>

            <h3><%= link_to "Remove", rv_path(rv), method: :delete, data: { confirm: 'Are you sure?' } %></h3>
      </div>




      <% if rv.bookings.length != 0 %>
        <p>Bookings for this rv: </p>
        <% rv.bookings.reverse_each do |b| %>
          <div class="row">
            <div class="col-xs-12 col-sm-10">
              <div class="reservation">
                <img class="avatar-large" src="http://via.placeholder.com/40x40">
                <div class="reservation-name">
                  <p><%= b.user.first_name %> <%= b.user.last_name %></p>
                </div>
                <div class="reservation-date">
                  <p><%= b.check_in_on %> <%= b.check_out_on %></p>
                </div>
                <div class="reservation-price">
                  <p><%= b.price %></p>
                </div>
                <% if (b.status == "Pending") %>
                  <div class="status-buttons inline">
                    <%= simple_form_for [rv, b] do |t| %>
                    <%= t.hidden_field :status, :value => "Accepted" %>
                    <%= t.submit "Accept", class: "btn btn-success" %>

                  <% end %>
                  <div class="placeholder"></div>
                  <%= simple_form_for [rv, b] do |t| %>
                    <%= t.hidden_field :status, :value => "Cancelled" %>
                    <%= t.submit "Cancel", class: "btn btn-danger" %>
                    <% end %>
                  </div>
                  <% else %>
                    <div class="status">
                    <%= b.status %>
                    </div>
                <% end %>

              </div>
            </div>
          </div>
        <% end %>

      <% else %>
        <p>No bookings for this RV.</p>

      <% end %>

    </div>
    <% end %>

</div>

app/views/rvs/new.html.erb
<%= render 'form' %>

app/views/rvs/show.html.erb
 <div class="container">
  <!-- Responsive display photo left and map right -->
  <div class="row" style="margin-top: 20px;">
    <!-- Display photo of RV if present, otherwise placeholder with unsplash -->
    <div class="col-xs-12 col-md-8">
      <div class="rv1">
        <% if @rv.photo? %>
          <%= cl_image_tag @rv.photo.path, width:730, height: 300 %>
        <% else %>
          <%= image_tag 'https://source.unsplash.com/FjtE9VKlKg4/730x300' %>
        <% end %>
      </div>
    </div>
    <!-- Display location of RV -->
    <div class="col-xs-12 col-md-4">
      <div class="rv1">
        <div id="map" style="width: 400; height: 300px;" ></div>
        <% content_for(:after_js) do %>
          <script>
            var handler = Gmaps.build('Google');
            handler.buildMap({ internal: { id: 'map' } }, function() {
              markers = handler.addMarkers(<%= raw @hash.to_json %>);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
              if (markers.length == 0) {
                handler.getMap().setZoom(2);
              } else if (markers.length == 1) {
                handler.getMap().setZoom(14);
              }
            });
          </script>
        <% end %>
      </div>
    </div>
  </div>
  <!-- Responsive display infos on left and call to action / booking form on right -->
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <div class="infos">
        <h2><%= @rv.name %></h2>
        <p>Rent this cool rv from <%= @rv.user.first_name %><%= @rv.user.last_name %></p>
        <p>This <%= @rv.kind.downcase %> recreational vehicle has <%= @rv.number_of_beds %> beds and can therefore comfortably accomodate up to <%= @rv.number_of_guests %> people</p>
        <p>It is currently located in <%= @rv.localisation %></p>
        <p>The minimum stay is <%= @rv.min_stay %> days</p>
        <h4>Price per night: <%= @rv.price_per_night %>$</h4>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="infos" id="newbook">
        <div class="vertical-flex">
          <% if @rv.user_id != current_user %>
            <%= render 'bookings/new', booking: @booking, rv: @rv %>
            <!-- <%= link_to "Make a booking", new_rv_booking_path(@rv), class:"btn btn-primary" %> -->
          <% end %>
          <!-- <%= link_to "Back to all RVs", root_path, class:"btn btn-primary" %> -->
        </div>
      </div>
    </div>
  </div>
  <div class="reviews">
    <h2>Reviews</h2>
      <% @rv.bookings.each do |b| %>
        <div class="row" id="list-reviews">
          <div class='col-md-2'><%= b.user.photo %></div>
          <div class="col-md-1"><%= "*" * b.rating %></div>
          <div class="col-md-9"><%= b.review %></div>
        </div>
      <% end %>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="header-banner-top">

      <div class="banner">

          <div class="banner-image"></div>

          <div class="primary-wrapper">

            <h1 class="site-title"><a href="#">MCRVS</a></h1>
            <div class="site-tagline"> Explore. Discover. Rent a recreational vehicle that fits your adventure.</div>
          </div>
          <div class="in-line">
          <%= link_to "Find a RV", root_path( anchor: "map"),  id: "go-down", :class => "btn-medium"%>
          <% if user_signed_in? %>
          <%= link_to "Add a RV", new_rv_path, :class => "btn-medium" %>
          <% end %>
          </div>
        </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to "MCRVS", root_path, class: "navbar-wagon-link" %>
    <!--<%= image_tag "logo.png" %>-->


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to  "My RVs", myrvs_path, class: "navbar-wagon-item navbar-wagon-link active-link" %>
      <%= link_to "Trips", bookings_path, class: "navbar-wagon-item navbar-wagon-link active-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link active-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://via.placeholder.com/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>